# Generated by Django 3.1.1 on 2022-12-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ig',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('posts', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('privacy', models.CharField(max_length=10)),
            ],
        ),
    ]
