# Generated by Django 3.1.1 on 2022-12-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ig',
            options={'permissions': (('view_reels', 'can view number of reels'), ('view_username', 'can access username'))},
        ),
    ]
